### PR TITLE
feature-rootOverlay

### LINKED ISSUE #7: [feature] Overlay.of let us use useRootNavigator
As a developer, i want to use useRootNavigator when my overlay is launched from a nested root.

### PR DESCRIPTION
**Pull request by EArminjon**
Fix https://github.com/ivofernandes/pinch_zoom_release_unzoom/issues/7

### CODE REVIEW

**Comment by EArminjon** [comment]
DRAFT

**Comment by ivofernandes** [comment]
Thank you so much :) 

Can you also add on the example application something that replicates the problem and solution?

For this cases is very useful to have something with a checkbox that we can test with the flag on or off and see what happens with this feature.


Take a look in this part of the example with the bottom navigation and the pages with different use cases
https://github.com/ivofernandes/pinch_zoom_release_unzoom/blob/master/example/lib/main.dart#L46

**Comment by EArminjon** [comment]
Hello @ivofernandes  you can now test it ;)

Inside nested Navigator overlay and base image are not aligned which is an other issue.

In my app i need to display overlay in first plan that's why this PR is created. Thanks of rootOverlay, i can display an overlay which cover all the app.

**Comment by ivofernandes** [comment]
Amazing thanks :) tomorrow will be published on pubdev :)

**Pull request merged**
