### PR TITLE
ScrollablePositionedList sample

### PR DESCRIPTION
**Pull request by StigUK**
ScrollablePositionedList sample with use the twoFingersOn param to avoid scroll when the user has two fingers on the screen

### CODE REVIEW

**Comment by ivofernandes** [comment]
Amazing, thanks for the contribution :)

**Comment by StigUK** [comment]
Is there any way to turn off zoom with three fingers?
[Video example](https://www.youtube.com/shorts/6wcKHljfkwo)

**Comment by ivofernandes** [comment]
Yes you can take a look here:

https://github.com/ivofernandes/pinch_zoom_release_unzoom/blob/master/lib/src/pinch_zoom_release_unzoom_widget.dart#L168

The listener returns you the number of fingers touching the screen

**Comment by ivofernandes** [comment]
I think what you want in that case is to not use the pinch to zoom widget when the 3rd finger appears

**Pull request merged**
